'use client';
import { useEffect, useMemo, useState } from 'react';
import { createClient } from '@/lib/supabase/client';

type Role = 'teacher'|'parent'|'principal';
type Profile={id:string;school_id:string;role:Role;full_name:string};
type Update={id:string;student_id:string;category:string;title:string;message:string;importance:'normal'|'important';sent_at:string;acknowledgements?:{acknowledged_at:string;parent_id:string}[];students?:{full_name:string};profiles?:{full_name:string}};
const categories=['academic','attendance','achievement','behaviour','homework_task','general'];
const nice=(s:string)=>s.replace('_',' ').replace(/\b\w/g,c=>c.toUpperCase());

export default function Page(){const db=useMemo(createClient,[]);const[p,setP]=useState<Profile|null>(null);const[busy,setBusy]=useState(true);const[error,setError]=useState('');const[email,setEmail]=useState('');const[password,setPassword]=useState('');
 const load=async()=>{setBusy(true);const{data:{user}}=await db.auth.getUser();if(!user){setP(null);setBusy(false);return}const{data,error}=await db.from('profiles').select('id,school_id,role,full_name').eq('id',user.id).single();setP(error?null:data as Profile);if(error)setError('Your profile could not be loaded.');setBusy(false)};
 useEffect(()=>{load();const{x}=db.auth.onAuthStateChange(load);return()=>x.subscription.unsubscribe()},[db]);
 if(busy)return <main className="center">Loading Schovera…</main>;
 if(!p)return <main className="login"><section><b className="logo">S</b><p className="eyebrow">SCHOVERA</p><h1>School. Home.<br/>Together.</h1><p>Trusted school communication, clearly connected.</p></section><form className="card" onSubmit={async e=>{e.preventDefault();setError('');const{error}=await db.auth.signInWithPassword({email,password});if(error)setError('Sign-in failed. Check your credentials.')}}><h2>Welcome back</h2><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="error">{error}</p>}<button>Sign in securely</button></form></main>;
 return <main className="app"><header><div><b className="logo small">S</b> <strong>SCHOVERA</strong></div><div>{p.full_name} <button className="link" onClick={()=>db.auth.signOut()}>Sign out</button></div></header><p className="eyebrow">{p.role}</p><h1>{p.role==='teacher'?'Keep every family informed.':p.role==='parent'?"Your child's school updates.":'Communication, clearly connected.'}</h1>{p.role==='teacher'?<Teacher p={p}/>:p.role==='parent'?<Parent p={p}/>:<Principal p={p}/>}</main>}

function Teacher({p}:{p:Profile}){const db=useMemo(createClient,[]);const[classes,setClasses]=useState<any[]>([]),[students,setStudents]=useState<any[]>([]),[classId,setClassId]=useState(''),[student,setStudent]=useState<any>(null),[updates,setUpdates]=useState<Update[]>([]),[note,setNote]=useState('');
 useEffect(()=>{db.from('teacher_class_assignments').select('classes(id,grade,division)').eq('teacher_id',p.id).is('ended_at',null).then(({data})=>setClasses((data||[]).map((x:any)=>x.classes).filter(Boolean)))},[db,p]);
 useEffect(()=>{if(classId)db.from('students').select('*').eq('class_id',classId).eq('active',true).order('full_name').then(({data})=>setStudents(data||[]))},[db,classId]);
 const refresh=async()=>{if(!student)return;const{data}=await db.from('student_updates').select('*,acknowledgements(acknowledged_at,parent_id)').eq('student_id',student.id).order('sent_at',{ascending:false});setUpdates(data||[])};
 useEffect(()=>{refresh()},[student]);useEffect(()=>{const c=db.channel('teacher-acks').on('postgres_changes',{event:'*',schema:'public',table:'acknowledgements'},refresh).subscribe();return()=>{db.removeChannel(c)}},[db,student]);
 async function send(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!student)return;const f=new FormData(e.currentTarget);setNote('');const{error}=await db.rpc('send_student_update',{p_class_id:classId,p_student_id:student.id,p_category:f.get('category'),p_title:f.get('title'),p_message:f.get('message'),p_importance:f.get('important')?'important':'normal'});if(error)setNote('Could not send update. Try again.');else{e.currentTarget.reset();setNote('Update sent and saved.');refresh()}}
 return <section className="two"><div className="card"><h2>1. Select class</h2><div className="chips">{classes.map(c=><button key={c.id} className={classId===c.id?'active':''} onClick={()=>{setClassId(c.id);setStudent(null)}}>Grade {c.grade}{c.division}</button>)}</div><h2>2. Select student</h2>{classId?students.map(s=><button className={student?.id===s.id?'student active':'student'} key={s.id} onClick={()=>setStudent(s)}>{s.full_name}<small>Roll {s.roll_number}</small></button>):<p>Select a class to view students.</p>}</div><div className="card">{student?<><p className="eyebrow">{student.full_name}</p><h2>Send parent update</h2><form onSubmit={send}><label>Category<select name="category">{categories.map(c=><option key={c}>{nice(c)}</option>)}</select></label><label>Title<input name="title" required minLength={3} maxLength={120} placeholder="Clear update title"/></label><label>Message<textarea name="message" required minLength={3} maxLength={1000} rows={4} placeholder="Write a short, kind, specific update…"/></label><label className="check"><input name="important" type="checkbox"/> Important — acknowledgement required</label><button>Send update</button></form>{note&&<p className={note.startsWith('Could')?'error':'success'}>{note}</p>}<h2>History</h2>{updates.map(u=><Card key={u.id} u={u} teacher/> )}</>:<p className="empty">Choose a student to create a clear, structured parent update.</p>}</div></section>}

function Parent({p}:{p:Profile}){const db=useMemo(createClient,[]);const[children,setChildren]=useState<any[]>([]),[id,setId]=useState(''),[updates,setUpdates]=useState<Update[]>([]);
 useEffect(()=>{db.from('parent_student_links').select('students(*)').eq('parent_id',p.id).eq('status','active').then(({data})=>{const x=(data||[]).map((r:any)=>r.students);setChildren(x);setId(x[0]?.id||'')})},[db,p]);
 const refresh=async()=>{if(!id)return;const{data}=await db.from('student_updates').select('*,profiles!student_updates_teacher_id_fkey(full_name),acknowledgements(acknowledged_at,parent_id)').eq('student_id',id).order('sent_at',{ascending:false});setUpdates(data||[])};useEffect(()=>{refresh()},[id]);useEffect(()=>{const c=db.channel('parent-updates').on('postgres_changes',{event:'INSERT',schema:'public',table:'student_updates'},refresh).subscribe();return()=>{db.removeChannel(c)}},[db,id]);
 return <section className="timeline"><div className="card"><label>Child<select value={id} onChange={e=>setId(e.target.value)}>{children.map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select></label><p>Important updates require acknowledgement. Normal updates are for your information.</p></div>{updates.map(u=><Card key={u.id} u={u} parent={p.id} acknowledge={async updateId=>{await db.rpc('acknowledge_update',{p_update_id:updateId});refresh()}}/>)}{id&&!updates.length&&<p className="empty">You’re all caught up. No updates yet.</p>}</section>}

function Principal({p}:{p:Profile}){const db=useMemo(createClient,[]);const[all,setAll]=useState<Update[]>([]);const refresh=async()=>{const{data}=await db.from('student_updates').select('*,students(full_name),acknowledgements(acknowledged_at)').eq('school_id',p.school_id).order('sent_at',{ascending:false});setAll(data||[])};useEffect(()=>{refresh();const c=db.channel('principal-coverage').on('postgres_changes',{event:'*',schema:'public',table:'student_updates'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'acknowledgements'},refresh).subscribe();return()=>{db.removeChannel(c)}},[db,p]);const important=all.filter(u=>u.importance==='important'),ack=important.filter(u=>u.acknowledgements?.length);return <section><div className="metrics">{[['Total updates',all.length],['Important',important.length],['Acknowledged',ack.length],['Awaiting',important.length-ack.length]].map(([a,b])=><div className="card" key={String(a)}><small>{a}</small><b>{b}</b></div>)}</div><div className="card"><p className="eyebrow">RECENT ACTIVITY</p><h2>Communication coverage, not teacher scoring.</h2>{all.slice(0,6).map(u=><Card key={u.id} u={u} teacher/> )}</div></section>}
function Card({u,teacher,parent,acknowledge}:{u:Update;teacher?:boolean;parent?:string;acknowledge?:(id:string)=>void}){const mine=u.acknowledgements?.find(a=>a.parent_id===parent);return <article><span className="badge">{nice(u.category)}</span>{u.importance==='important'&&<span className="important">Acknowledgement required</span>}<h3>{u.title}</h3><p>{u.message}</p><small>{u.profiles?.full_name&&`${u.profiles.full_name} · `}{u.students?.full_name&&`${u.students.full_name} · `}{new Date(u.sent_at).toLocaleString()}</small>{u.importance==='important'&&<div className="ack">{mine||(!parent&&u.acknowledgements?.length)?<b className="success">Acknowledged</b>:teacher?<span>Awaiting acknowledgement</span>:<button onClick={()=>acknowledge?.(u.id)}>Acknowledge update</button>}</div>}</article>}
