-- Safe for a fresh project or either partial state from prior failed attempts.
-- It never drops tables, rows, Auth users, or existing business data.
create extension if not exists pgcrypto;
do $$ begin create type public.app_role as enum ('teacher','parent','principal'); exception when duplicate_object then null; end $$;
do $$ begin create type public.update_category as enum ('academic','attendance','achievement','behaviour','homework_task','general'); exception when duplicate_object then null; end $$;
do $$ begin create type public.update_importance as enum ('normal','important'); exception when duplicate_object then null; end $$;

create table if not exists public.schools (id uuid primary key default gen_random_uuid(), name text not null check (char_length(name) between 2 and 160), code text not null unique, timezone text not null default 'Asia/Kolkata', logo_url text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, school_id uuid not null references public.schools(id) on delete restrict, role public.app_role not null, full_name text not null check (char_length(full_name) between 2 and 120), email text not null, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(school_id,email));
create table if not exists public.classes (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete restrict, grade text not null, division text not null, academic_year text not null, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(school_id,grade,division,academic_year));
create table if not exists public.teacher_class_assignments (id uuid primary key default gen_random_uuid(), teacher_id uuid not null references public.profiles(id) on delete restrict, class_id uuid not null references public.classes(id) on delete restrict, assigned_at timestamptz not null default now(), ended_at timestamptz, unique(teacher_id,class_id));
create table if not exists public.students (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete restrict, class_id uuid not null references public.classes(id) on delete restrict, roll_number text not null, full_name text not null, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(class_id,roll_number));
create table if not exists public.parent_student_links (id uuid primary key default gen_random_uuid(), parent_id uuid not null references public.profiles(id) on delete restrict, student_id uuid not null references public.students(id) on delete restrict, relationship_label text, status text not null default 'active' check(status in ('active','inactive')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(parent_id,student_id));
create table if not exists public.student_updates (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete restrict, class_id uuid not null references public.classes(id) on delete restrict, student_id uuid not null references public.students(id) on delete restrict, teacher_id uuid not null references public.profiles(id) on delete restrict, category public.update_category not null, title text not null check(char_length(title) between 3 and 120), message text not null check(char_length(message) between 3 and 1000), importance public.update_importance not null default 'normal', status text not null default 'sent' check(status in ('sent','archived')), sent_at timestamptz not null default now(), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.acknowledgements (id uuid primary key default gen_random_uuid(), update_id uuid not null references public.student_updates(id) on delete restrict, parent_id uuid not null references public.profiles(id) on delete restrict, acknowledged_at timestamptz not null default now(), created_at timestamptz not null default now(), unique(update_id,parent_id));
create table if not exists public.audit_events (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete restrict, actor_id uuid references public.profiles(id) on delete set null, event_type text not null, target_type text not null, target_id uuid, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create index if not exists student_updates_student_sent_idx on public.student_updates(student_id,sent_at desc);
create index if not exists student_updates_school_sent_idx on public.student_updates(school_id,sent_at desc);
create index if not exists parent_links_parent_idx on public.parent_student_links(parent_id,status);
create index if not exists acknowledgement_update_idx on public.acknowledgements(update_id,acknowledged_at);

-- Scalar helpers deliberately avoid a composite public.profiles return type.
create or replace function public.current_user_role() returns text language sql stable security definer set search_path = public, pg_temp as $$ select p.role::text from public.profiles p where p.id = auth.uid() and p.active = true $$;
create or replace function public.current_user_school_id() returns uuid language sql stable security definer set search_path = public, pg_temp as $$ select p.school_id from public.profiles p where p.id = auth.uid() and p.active = true $$;
create or replace function public.same_school(target_school uuid) returns boolean language sql stable security definer set search_path = public, pg_temp as $$ select public.current_user_school_id() = target_school $$;

alter table public.schools enable row level security; alter table public.profiles enable row level security; alter table public.classes enable row level security; alter table public.teacher_class_assignments enable row level security; alter table public.students enable row level security; alter table public.parent_student_links enable row level security; alter table public.student_updates enable row level security; alter table public.acknowledgements enable row level security; alter table public.audit_events enable row level security;
drop policy if exists "own school" on public.schools; drop policy if exists "own profile" on public.profiles; drop policy if exists "assigned or linked class" on public.classes; drop policy if exists "own assignment" on public.teacher_class_assignments; drop policy if exists "authorized students" on public.students; drop policy if exists "own parent links" on public.parent_student_links; drop policy if exists "authorized updates" on public.student_updates; drop policy if exists "authorized acknowledgement read" on public.acknowledgements;
create policy "own school" on public.schools for select using (public.same_school(schools.id));
create policy "own profile" on public.profiles for select using (profiles.id = auth.uid() or (public.current_user_role() = 'principal' and public.same_school(profiles.school_id)));
create policy "assigned or linked class" on public.classes for select using ((public.current_user_role() = 'principal' and public.same_school(classes.school_id)) or exists(select 1 from public.teacher_class_assignments a where a.class_id = classes.id and a.teacher_id = auth.uid() and a.ended_at is null) or exists(select 1 from public.students s join public.parent_student_links l on l.student_id=s.id where s.class_id=classes.id and l.parent_id=auth.uid() and l.status='active'));
create policy "own assignment" on public.teacher_class_assignments for select using (teacher_class_assignments.teacher_id=auth.uid() or (public.current_user_role() = 'principal' and exists(select 1 from public.classes c where c.id=teacher_class_assignments.class_id and public.same_school(c.school_id))));
create policy "authorized students" on public.students for select using ((public.current_user_role() = 'principal' and public.same_school(students.school_id)) or exists(select 1 from public.teacher_class_assignments a where a.class_id=students.class_id and a.teacher_id=auth.uid() and a.ended_at is null) or exists(select 1 from public.parent_student_links l where l.student_id=students.id and l.parent_id=auth.uid() and l.status='active'));
create policy "own parent links" on public.parent_student_links for select using (parent_student_links.parent_id=auth.uid() or (public.current_user_role() = 'principal' and exists(select 1 from public.students s where s.id=parent_student_links.student_id and public.same_school(s.school_id))));
create policy "authorized updates" on public.student_updates for select using ((public.current_user_role() = 'principal' and public.same_school(student_updates.school_id)) or student_updates.teacher_id=auth.uid() or exists(select 1 from public.parent_student_links l where l.student_id=student_updates.student_id and l.parent_id=auth.uid() and l.status='active'));
create policy "authorized acknowledgement read" on public.acknowledgements for select using (acknowledgements.parent_id=auth.uid() or exists(select 1 from public.student_updates u where u.id=acknowledgements.update_id and (u.teacher_id=auth.uid() or (public.current_user_role() = 'principal' and public.same_school(u.school_id)))));

create or replace function public.send_student_update(p_class_id uuid,p_student_id uuid,p_category public.update_category,p_title text,p_message text,p_importance public.update_importance) returns uuid language plpgsql security definer set search_path = public, pg_temp as $$ declare actor_school uuid; actor_role text; created_update_id uuid; begin actor_role:=public.current_user_role(); actor_school:=public.current_user_school_id(); if actor_role <> 'teacher' or not exists(select 1 from public.teacher_class_assignments a where a.teacher_id=auth.uid() and a.class_id=p_class_id and a.ended_at is null) then raise exception 'not authorized'; end if; if not exists(select 1 from public.students s where s.id=p_student_id and s.class_id=p_class_id and s.school_id=actor_school and s.active) then raise exception 'student not in assigned class'; end if; insert into public.student_updates as update_row(school_id,class_id,student_id,teacher_id,category,title,message,importance) values(actor_school,p_class_id,p_student_id,auth.uid(),p_category,p_title,p_message,p_importance) returning update_row.id into created_update_id; insert into public.audit_events(school_id,actor_id,event_type,target_type,target_id) values(actor_school,auth.uid(),'student_update_sent','student_update',created_update_id); return created_update_id; end $$;
create or replace function public.acknowledge_update(p_update_id uuid) returns void language plpgsql security definer set search_path = public, pg_temp as $$ declare update_school uuid; begin if public.current_user_role() <> 'parent' then raise exception 'not authorized'; end if; select u.school_id into update_school from public.student_updates u join public.parent_student_links l on l.student_id=u.student_id where u.id=p_update_id and l.parent_id=auth.uid() and l.status='active'; if update_school is null then raise exception 'not authorized'; end if; insert into public.acknowledgements(update_id,parent_id) values(p_update_id,auth.uid()) on conflict(update_id,parent_id) do nothing; insert into public.audit_events(school_id,actor_id,event_type,target_type,target_id) values(update_school,auth.uid(),'student_update_acknowledged','student_update',p_update_id); end $$;
revoke execute on function public.current_user_role() from public;
revoke execute on function public.current_user_school_id() from public;
revoke execute on function public.same_school(uuid) from public;
revoke execute on function public.send_student_update(uuid,uuid,public.update_category,text,text,public.update_importance) from public;
revoke execute on function public.acknowledge_update(uuid) from public;
grant execute on function public.current_user_role() to authenticated;
grant execute on function public.current_user_school_id() to authenticated;
grant execute on function public.same_school(uuid) to authenticated;
grant execute on function public.send_student_update(uuid,uuid,public.update_category,text,text,public.update_importance) to authenticated;
grant execute on function public.acknowledge_update(uuid) to authenticated;
do $$ begin if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='student_updates') then alter publication supabase_realtime add table public.student_updates; end if; if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='acknowledgements') then alter publication supabase_realtime add table public.acknowledgements; end if; end $$;
